# Generated by Django 3.0.2 on 2020-02-25 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_test', '0002_remove_answerstudent_answer_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerstudent',
            options={'verbose_name': 'Ответ студента', 'verbose_name_plural': 'Ответы студентов'},
        ),
        migrations.AddField(
            model_name='answerstudent',
            name='answer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_test.Answer'),
        ),
    ]
