# Generated by Django 3.0.2 on 2020-02-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_test', '0003_auto_20200225_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerstudent',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
