# Generated by Django 3.0.2 on 2020-02-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_test', '0004_answerstudent_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerstudent',
            name='status',
        ),
    ]
