# Generated by Django 3.0.2 on 2020-02-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_test', '0005_remove_answerstudent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerstudent',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
