# Generated by Django 3.0.2 on 2020-02-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module_test', '0006_answerstudent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerstudent',
            name='test',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_test.Test'),
        ),
    ]
